language: node_js
node_js:
  - "stable"
    
addons:
  ssh_known_hosts: git.ionicjs.com
  
sudo: required

branches:
  only:
    - firestore

before_script:
  - npm install -g firebase-tools
  - npm install -g ionic
  - npm install -g cordova

script:
  - ionic build --platform browser

after_success:  
  - ionic monitoring syncmaps
  - ionic login ${IONIC_EMAIL} ${IONIC_PASSWORD}
  - ionic link --pro-id d215c909
  - ionic ssh setup
  - ionic git remote
  
deploy:
  - firebase deploy --token "${FIREBASE_TOKEN}"
  - git push ionic HEAD:master
