language: node_js
node_js:
  - "stable"
    
addons:
  ssh_known_hosts: git.ionicjs.com
  
sudo: required

branches:
  only:
    - firestore

before_script:
  - npm install -g firebase-tools
  - npm install -g ionic
  - npm install -g cordova

script:
  - ionic build --platform browser

after_success:  
  - firebase deploy --token "${FIREBASE_TOKEN}"
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/deploy_rsa
  - ssh-add ./.travis/deploy_rsa
  - ionic monitoring syncmaps
  - ionic link --pro-id d215c909
  - ionic git remote  
  - git push ionic HEAD:master
