language: node_js
node_js:
  - "stable"

branches:
  only:
    - firestore
    
addons:
  ssh_known_hosts: git.ionicjs.com

before_script:
  - npm install -g firebase-tools
  - npm install -g ionic
  - npm install -g cordova

script:
  - ionic build --platform browser

after_success:
  - firebase deploy --token "${FIREBASE_TOKEN}"
  - ionic monitoring syncmaps
  - ionic login ${IONIC_EMAIL} ${IONIC_PASSWORD}
  - ionic link --pro-id d215c909
  - ionic git remote
  - git push git@git.ionicjs.com:acharya/elms.git --origin=ionic
